In [2]:
import pandas as pd
import nba_api

In [3]:
from nba_api.stats.endpoints import playercareerstats
# Anthony Davis
career = playercareerstats.PlayerCareerStats(player_id='203076')
career.get_data_frames()[0]

,PLAYER_ID,SEASON_ID,LEAGUE_ID,TEAM_ID,TEAM_ABBREVIATION,PLAYER_AGE,GP,GS,MIN,FGM,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS
0,203076,2012-13,00,1610612740,NOH,20.0,64,60,1846.0,349,...,0.751,165,357,522,63,75,112,89,158,867
1,203076,2013-14,00,1610612740,NOP,21.0,67,66,2358.0,522,...,0.791,207,466,673,105,89,189,109,200,1394
2,203076,2014-15,00,1610612740,NOP,22.0,68,68,2455.0,642,...,0.805,173,523,696,149,100,200,95,141,1656
3,203076,2015-16,00,1610612740,NOP,23.0,61,61,2164.0,560,...,0.758,130,497,627,116,78,125,121,148,1481
4,203076,2016-17,00,1610612740,NOP,24.0,75,75,2708.0,770,...,0.802,172,712,884,157,94,167,181,168,2099
5,203076,2017-18,00,1610612740,NOP,25.0,75,75,2727.0,780,...,0.828,187,644,831,174,115,193,162,159,2110
6,203076,2018-19,00,1610612740,NOP,26.0,56,56,1850.0,530,...,0.794,174,498,672,218,88,135,112,132,1452
7,203076,2019-20,00,1610612747,LAL,27.0,62,62,2131.0,551,...,0.846,142,435,577,200,91,143,154,156,1618
8,203076,2020-21,00,1610612747,LAL,28.0,36,36,1162.0,301,...,0.738,62,224,286,110,45,59,74,60,786
9,203076,2021-22,00,1610612747,LAL,29.0,40,40,1404.0,370,...,0.713,106,288,394,122,49,90,82,97,927

In [4]:
#Get the PHI team_id
from nba_api.stats.static import teams

nba_teams = teams.get_teams()

# Select the dictionary for the Pacers, which contains their team ID
sixers = [team for team in nba_teams if team['abbreviation'] == 'PHI'][0]
sixers_id = sixers['id']
print(f'sixers_id: {sixers_id}')

sixers_id: 1610612755

In [5]:
from nba_api.stats.endpoints import leaguegamefinder

# Query for games where the Sixers were playing
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=sixers_id)
# The first DataFrame of those returned is what we want.
games = gamefinder.get_data_frames()[0]
games.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42021,1610612755,PHI,Philadelphia 76ers,0042100206,2022-05-12,PHI vs. MIA,L,239,90,...,0.857,6,29,35,21,8.0,6,13,16,-9.0
1,42021,1610612755,PHI,Philadelphia 76ers,0042100205,2022-05-10,PHI @ MIA,L,241,85,...,0.933,10,26,36,14,8.0,2,15,19,-35.0
2,42021,1610612755,PHI,Philadelphia 76ers,0042100204,2022-05-08,PHI vs. MIA,W,239,116,...,0.765,4,28,32,25,5.0,2,16,24,8.0
3,42021,1610612755,PHI,Philadelphia 76ers,0042100203,2022-05-06,PHI vs. MIA,W,242,99,...,0.864,8,35,43,22,7.0,3,18,24,20.0
4,42021,1610612755,PHI,Philadelphia 76ers,0042100202,2022-05-04,PHI @ MIA,L,236,103,...,0.864,5,29,34,17,10.0,4,8,25,-16.0

In [8]:
games.groupby(games.SEASON_ID.str[-4:])[['GAME_ID']].count()

           GAME_ID
SEASON_ID
1983            87
1984            95
1985            94
1986            87
1987            82
1988            85
1989            92
1990            90
1991            82
1992            82
1993            82
1994            82
1995            82
1996            82
1997            82
1998            58
1999            92
2000           105
2001            87
2002            94
2003            83
2004            90
2005            89
2006            89
2007            99
2008           100
2009            91
2010            99
2011            81
2012            94
2013            94
2014           101
2015            97
2016            98
2017           105
2018           104
2019            90
2020            86
2021           103

In [10]:
games_21 = games[games.SEASON_ID.str[-4:] == '2021']
games_21.head()

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,42021,1610612755,PHI,Philadelphia 76ers,0042100206,2022-05-12,PHI vs. MIA,L,239,90,...,0.857,6,29,35,21,8.0,6,13,16,-9.0
1,42021,1610612755,PHI,Philadelphia 76ers,0042100205,2022-05-10,PHI @ MIA,L,241,85,...,0.933,10,26,36,14,8.0,2,15,19,-35.0
2,42021,1610612755,PHI,Philadelphia 76ers,0042100204,2022-05-08,PHI vs. MIA,W,239,116,...,0.765,4,28,32,25,5.0,2,16,24,8.0
3,42021,1610612755,PHI,Philadelphia 76ers,0042100203,2022-05-06,PHI vs. MIA,W,242,99,...,0.864,8,35,43,22,7.0,3,18,24,20.0
4,42021,1610612755,PHI,Philadelphia 76ers,0042100202,2022-05-04,PHI @ MIA,L,236,103,...,0.864,5,29,34,17,10.0,4,8,25,-16.0